# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80d7048ed6fc1f5dea5b38441696ad2b6658dcb26223ff043ed7e04cb9a6c3e4ed8aedfda6612fd2a0873fe1e6e2995979137954c1ac6eab58159a0f07bd67d7

test:
  secret_key_base: d959aa39d698da63b2ddcbe2286f4d8e56921c1eb26bb0bea5e51a163496f5d6fc38cb192d57d5f5a704cae31742fa64b9a4ba4023aa2af8c045eaf08f900a32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
